name: Periodic Health Check
  
on:
  schedule:
  - cron:  '59 23 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://full-stack-open-pokedex-rze0.onrender.com/health
          max-attempts: 3
          retry-delay: 5s 